### PR TITLE
sidepanel toggle

### LINKED ISSUE #67: Make website responsive 500px
may drop this in our initial "finish the project" if its too large

### PR DESCRIPTION
**Pull request by ajo01**
responsive

Closes #67 

Note: I coded this on a laptop. Please check if it's still responsive on your screens.

### CODE REVIEW

**Comment by duffydu** [comment]
Hi Amy, this looks great! It works on my laptop. I'm just wondering, when it collapse to the left panel for small screens, is it possible to collapse left panel when the user clicks on a chat. I think it makes more sense when the user clicks on a chat, they want to see the contents of it :)

**Comment by ajo01** [comment]
hi @duffydu! Thanks for the feedback. I agree with your thoughts and have made the change.

**Comment by kylexrich** [comment]
Love it!

**Review by kylexrich — APPROVED** [review]
Love it x2

**Review by duffydu — APPROVED** [review]

**Pull request merged**
