### PR TITLE
Typewriter animation

### LINKED ISSUE #43: Typewriter animation
Refer to ChatGPT
ideas:
Consider adding an animationRendered property to the message model so the frontend knows not to animate messages that already animated
Check timestamp the message was created

### PR DESCRIPTION
**Pull request by ajo01**
Closes #43
typewriter

tada! The animation's done. Only messages that have been created in the past 5 seconds will be animated. Might want to change the logic for this later though.
Still needs a loading state.

### CODE REVIEW

**Review by huangcar1 — APPROVED** [review]
your front end skills >>>

**Comment by huangcar1** [comment]
> Love it! Nice simple package too. Are we able to change the delay to like 10 or 15 though? Up to majority, but I personally think 20 is too slow.

I think 20 is fine, but am ok w/ 10 or 15 too!

**Comment by ajo01** [comment]
I'm ok with either. I felt 20 was great for short sentences while 10 was good for long passages. In fact, I'll keep the speed dynamic.

**Review by kylexrich — APPROVED** [review]
Dynamic approach!! Fantastic.

**Review by ritikk7 — APPROVED** [review]

**Pull request merged**
